# Generated by Django 4.1.5 on 2023-06-02 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estrategia',
            fields=[
                ('id_estrategia', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Estrategias',
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id_meta', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id_mision', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Mision',
            },
        ),
        migrations.CreateModel(
            name='Politica',
            fields=[
                ('id_politica', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Regla',
            fields=[
                ('id_regla', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('politica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BMM.politica')),
            ],
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id_vision', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('mision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BMM.mision')),
            ],
            options={
                'verbose_name_plural': 'Vision',
            },
        ),
        migrations.CreateModel(
            name='Tacticas',
            fields=[
                ('id_tactica', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('estrategia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BMM.estrategia')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BMM.meta')),
                ('regla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BMM.regla')),
            ],
            options={
                'verbose_name_plural': 'Tacticas',
            },
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id_objetivo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('vision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BMM.vision')),
            ],
            options={
                'verbose_name_plural': 'Objetivos',
            },
        ),
        migrations.AddField(
            model_name='meta',
            name='objetivos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BMM.objetivo'),
        ),
        migrations.AddField(
            model_name='estrategia',
            name='mision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BMM.mision'),
        ),
        migrations.AddField(
            model_name='estrategia',
            name='objectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BMM.objetivo'),
        ),
        migrations.AddField(
            model_name='estrategia',
            name='politica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BMM.politica'),
        ),
    ]
