# Generated by Django 4.1.5 on 2023-06-02 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('direcccion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Maniqui',
            fields=[
                ('id_maniqui', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=100)),
                ('tamaño', models.CharField(max_length=100)),
                ('diseño', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Maniquies',
            },
        ),
        migrations.CreateModel(
            name='ThermoSoplado',
            fields=[
                ('id_Thermo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'ThermoSoplado',
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id_produccion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ontologico.thermosoplado')),
            ],
            options={
                'verbose_name_plural': 'Produccion',
            },
        ),
        migrations.CreateModel(
            name='Distribucion',
            fields=[
                ('id_distribucion', models.AutoField(primary_key=True, serialize=False)),
                ('direccionEntrega', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ontologico.thermosoplado')),
            ],
            options={
                'verbose_name_plural': 'Empaquetado y Distribucion',
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id_control', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('produccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ontologico.produccion')),
            ],
            options={
                'verbose_name_plural': 'Control de calidad',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_Thermo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('valor', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ontologico.cliente')),
                ('distribucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ontologico.distribucion')),
                ('maniqui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ontologico.maniqui')),
            ],
            options={
                'verbose_name_plural': 'Almacenamiento',
            },
        ),
        migrations.CreateModel(
            name='Almacenamiento',
            fields=[
                ('id_almacenamiento', models.AutoField(primary_key=True, serialize=False)),
                ('Stock', models.CharField(max_length=100)),
                ('capacidad', models.CharField(max_length=100)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ontologico.thermosoplado')),
            ],
            options={
                'verbose_name_plural': 'Almacenamiento',
            },
        ),
    ]
