# Generated by Django 4.1.5 on 2023-06-02 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ontologico', '0001_initial'),
        ('E_Negocio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actores',
            fields=[
                ('id_actor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Actores',
            },
        ),
        migrations.CreateModel(
            name='ObjetoNegocio',
            fields=[
                ('id_linea', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('Tipo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Objeto de Negocio',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('TipoServicip', models.CharField(max_length=100)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='P_Servicios.actores')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='P_Servicios.objetonegocio')),
            ],
            options={
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Negocios',
            fields=[
                ('id_negocios', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Negocio.canales')),
                ('thermo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ontologico.thermosoplado')),
            ],
            options={
                'verbose_name_plural': 'Negocios',
            },
        ),
        migrations.CreateModel(
            name='LineaNegocio',
            fields=[
                ('id_linea', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('lineaNegocio', models.CharField(max_length=100)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='P_Servicios.negocios')),
            ],
            options={
                'verbose_name_plural': 'Linea de negocio',
            },
        ),
        migrations.AddField(
            model_name='actores',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='P_Servicios.negocios'),
        ),
    ]
