# Generated by Django 4.1.5 on 2023-06-02 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='Canales',
            fields=[
                ('id_canales', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Canales',
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id_participante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Participantes',
            },
        ),
        migrations.CreateModel(
            name='TipoCanal',
            fields=[
                ('id_recurso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Canales',
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id_recurso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Negocio.actividades')),
            ],
            options={
                'verbose_name_plural': 'Recursos',
            },
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id_componente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Negocio.canales')),
            ],
            options={
                'verbose_name_plural': 'Componentes',
            },
        ),
        migrations.AddField(
            model_name='canales',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Negocio.tipocanal'),
        ),
        migrations.AddField(
            model_name='actividades',
            name='canal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Negocio.canales'),
        ),
        migrations.AddField(
            model_name='actividades',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='E_Negocio.participante'),
        ),
    ]
